baseURL = "https://blog.incubator4.com/"
title = "Incubator4's Blog"
languageCode =  "zh-cn"
defaultContentLanguage = "zh"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
theme = "minimo"
disqusShortname = ""
googleAnalytics = ""
Paginate = 15
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true


[params.info]
description = "专注Golang,Docker,Kubernetes,云原生 等相关技术"
title404 = "走丢啦"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
#customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Incubator4"
startYear = "2018"
suffix = "<br><a style='font-weight:bold; font-style: normal' href=https://beian.miit.gov.cn/ >浙ICP备19012395号-1</a>"
[markup.goldmark.renderer]
unsafe= true
[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = false
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#66ccff"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
# codepen = "MunifTanjim"
email = "aries0robin@gmail.com"
# facebook = "MunifTanjim"
github = "Incubator4"
gitlab = "Incubator4"
# instagram = "MunifTanjim"
# linkedin = "muniftanjim"
# twitter = "MunifTanjim"
# telegram = "MunifTanjim"
# google_scholar = "qc6CJjYAAAAJ"
# youtube = "UCT-U0rNerYxItGcuoPX-WYA"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "Incubator4"
repository = "minimo"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "Incubator4"
repository = "minimo"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"


[[menu.main]]
name = "Home"
weight = -1
identifier = "home"
url =  "/"
[[menu.main]]
name = "Post"
weight = 5
identifier = "post"
url = "/post"
[[menu.main]]
name = "Tag"
weight = 40
identifier = "tag"
url = "/tags"
[[menu.main]]
name = "About"
weight = 90
identifier = "about"
url =  "/about"
[[menu.main]]
name = "Repo"
weight = 100
identifier = "repository"
url = "https://github.com/Incubator4th"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.zh]
lang = "zh"
languageName = "Chinese"
weight = 1
